# -*- coding: utf-8 -*-

import scrapy

class SegmentLeadersItem(scrapy.Item):
    amazon_title = scrapy.Field()
    asin = scrapy.Field()
    attributes = scrapy.Field()
    brand_id = scrapy.Field()
    brand_name = scrapy.Field()
    brand_slug = scrapy.Field()
    delivery_date = scrapy.Field()
    fba = scrapy.Field()
    first_available = scrapy.Field()
    gtin = scrapy.Field()
    height = scrapy.Field()
    length = scrapy.Field()
    meta_category = scrapy.Field()
    merchant_data = scrapy.Field()
    minimum_quantity = scrapy.Field()
    name = scrapy.Field()
    operation = scrapy.Field()
    parent_asin = scrapy.Field()
    prime_flag = scrapy.Field()
    product_id = scrapy.Field()
    product_name = scrapy.Field()
    product_url = scrapy.Field()
    product_price = scrapy.Field()
    product_summary = scrapy.Field()
    product_description = scrapy.Field()
    product_safety = scrapy.Field()
    product_dimension = scrapy.Field()
    product_image = scrapy.Field()
    product_quantity = scrapy.Field()
    product_type = scrapy.Field()
    product_condition = scrapy.Field()
    rerun = scrapy.Field()
    segment_category_id = scrapy.Field()
    segment_flag = scrapy.Field()
    segment_sku = scrapy.Field()
    slug = scrapy.Field()
    sku = scrapy.Field()
    supplier_id = scrapy.Field()
    supplier_url = scrapy.Field()
    supplier_name = scrapy.Field()
    shipping_cost = scrapy.Field()
    shipping_weight = scrapy.Field()
    suppliers_list_url = scrapy.Field()
    width = scrapy.Field()